const ALL_VOCAB_DATA = {
    'chap17': {
        title: 'Chapitre 17',
        selectorId: 'chap17SelectBtn',
        subcategories: {
            'noms': {
                name: 'Noms',
                color: '#FFA500',
                alert: {
                    message: "le voc est à jour ! utiliser le site afin d'étudier et de consolider vos connaissances !",
                    color: '#4CAF50'
                },
                data: [
                    ["délation", "dénonciation particulièrement méprisable", "nom"],
                    ["duplicité", "comportement hypocrite, jeu double", "nom"],
                    ["gloriole", "vanité, désir d'être admiré", "nom"],
                    ["impudence", "l'audace, l'effronterie", "nom"],
                    ["infamie", "action déshonorable, honteuse", "nom"],
                    ["malversations", "opérations malhonnêtes portant sur des sommes d'argent", "nom"],
                    ["parjure", "violation d'un serment", "nom"],
                    ["suffisance", "prétention, vanité", "nom"],
                    ["vergogne", "manque de pudeur ou de honte", "nom"],
                    ["tare", "infirmité ou défaut souvent d'ordre moral ou physique", "nom"],
                    ["infamie", "action honteuse", "nom"],
                    ["compromission", "acte qui compromet la réputation", "nom"],
                    ["malignité", "caractère méchant qui cherche à nuire", "nom"],
                    ["malversations", "détournements ou fraudes financières", "nom"],
                    ["outrage", "injure grave, offense à l'honneur de quelqu'un", "nom"],
                    ["outrecuidance", "effronterie, audace excessive", "nom"],
                    ["perfidie", "traîtrise, manquement à la parole donnée", "nom"],
                    ["perversion", "dépravation, dévoiement moral", "nom"],
                    ["sadisme", "plaisir à faire souffrir les autres", "nom"],
                    ["avilissement", "dénaturation morale, déchéance progressive", "nom"],
                    ["fatuité", "satisfaction excessive de soi-même", "nom"],
                    ["scélérat", "personne criminelle ou très coupable", "nom"],
                    ["vice", "grave défaut moral", "nom"],
                    ["imposteur", "qui se fait passer pour quelqu'un d'autre", "nom"]
                ]
            },
            'adjectifs': {
                name: 'Adjectifs',
                color: '#FFA500',
                data: [
                    ["cupide", "qui cherche constamment à obtenir le plus d'argent possible", "adjectif"],
                    ["importun", "qui dérange par sa présence", "adjectif"],
                    ["inique", "qui fait preuve d'injustice criante", "adjectif"],
                    ["mercantile", "orienté uniquement vers le profit", "adjectif"],
                    ["pédant", "qui fait l'étalage de son savoir", "adjectif"],
                    ["pernicieux", "nuisible moralement", "adjectif"],
                    ["volage", "qui n'est pas fidèle en amour", "adjectif"],
                    ["dépravé", "corrompu moralement", "adjectif"],
                    ["irascible", "qui se met en colère facilement", "adjectif"],
                    ["ignare", "ignorant, inculte", "adjectif"],
                    ["machiavélique", "rusé et prêt à tromper pour parvenir à ses fins", "adjectif"],
                    ["ignoble", "d'une bassesse morale inspirant le dégoût", "adjectif"],
                    ["opportuniste", "qui tire parti des circonstances sans principes", "adjectif"],
                    ["sectaire", "intolérant, aux opinions étroites", "adjectif"],
                    ["abject", "qui inspire la révolte et le mépris", "adjectif"],
                    ["répréhensible", "qui mérite d'être blâmé moralement", "adjectif"],
                    ["irrévérencieux", "insolent, qui manque de respect", "adjectif"],
                    ["impénitent", "qui ne regrette pas ses fautes", "adjectif"],
                    ["vindicatif", "qui cherche la vengeance", "adjectif"],
                    ["hâbleur", "qui se vante de manière exagérée", "adjectif"],
                    ["veule", "qui manque d'énergie et de volonté", "adjectif"],
                    ["pleutre", "lâche, sans courage physique", "adjectif"],
                    ["partisan", "inspiré par l'esprit de parti", "adjectif"],
                    ["ladre", "d'une avarice sordide", "adjectif"],
                    ["fatuité", "prétention ridicule", "nom"],
                    ["outrecuidant", "effronté, impertinent", "adjectif"],
                    ["scélérat", "criminel, infâme", "adjectif"],
                    ["vénal", "susceptible d'être acheté", "adjectif"],
                    ["maléfique", "qui exerce une influence mauvaise", "adjectif"]
                ]
            },
            'verbes': {
                name: 'Verbes',
                color: '#FFA500',
                data: [
                    ["duper", "tromper", "verbe"],
                    ["abuser", "tromper par de belles paroles; user avec excès", "verbe"],
                    ["léser", "causer préjudice, désavantager", "verbe"],
                    ["lésiner", "chercher à faire le minimum de dépenses", "verbe"]
                ]
            }
        }
    },
    'chap18': {
        title: 'Chapitre 18',
        selectorId: 'chap18SelectBtn',
        subcategories: {
            'general': {
                name: 'Chapitre 18',
                color: '#FFA500',
                alert: {
                    message: "l'évaluation est déjà passée. Cette liste est obsolète.",
                    color: '#FF8C00'
                },
                data: [
                    ["Austérité", "une politique qui impose des sacrifices", "nom f"],
                    ["Aversion", "un rejet total", "nom f"],
                    ["Altruiste", "qui dispose à s'intéresser et à se dévouer à autrui", "adjectif"],
                    ["Animosité", "malveillance", "nom f"],
                    ["Bouffon(ne)", "comique par son ridicule", "adjectif"],
                    ["Commisération", "de la pitié, de la compassion pour des personnes malheureuses ou inférieures", "nom f"],
                    ["Courroux", "une violente colère", "nom"],
                    ["Des moments d'exaltation", "d'enthousiaste, de surexcitation", "nom f"],
                    ["Félicité", "un bonheur total et paisible généralement durable (terme littéraire et religieux)", "nom f"],
                    ["Être féru(e)", "être passionné(e) par qqch", "adjectif"],
                    ["Une conversation galante", "amoureuse, romantique", "nom f"],
                    ["Idylle", "une aventure amoureuse tendre et naïve", "nom f"],
                    ["Faire preuve d'indulgence", "être tolérant, patient, excuser ou minimiser des fautes", "verbe"],
                    ["Une lutte sans merci", "sans pitié, sans grâce (vieilli)", "nom f"],
                    ["Suspicion", "sentiment de méfiance", "nom f"],
                    ["Réprobation", "sentiment résultant d'un jugement moral condamnant une action ou une conduite", "nom f"],
                    ["Quiétude", "état de tranquillité de l'âme, absence de soucis", "nom f"],
                    ["Pressentiment", "sentiment vague de ce qui va arriver, synonyme de prémonition", "nom m"],
                    ["Grief", "sujets de plainte contre une personne (généralement aux pluriel)", "nom m"],
                    ["Euphorie", "impression du bien-être proche du bonheur", "nom f"],
                    ["Gratitude", "sentiment de reconnaissance mêlé d'affection", "nom f"],
                    ["Effusion", "au singulier: action de verser du sang ; au pluriel: manifestation de tendresse, d'affection", "nom f"],
                    ["Amertume", "tristesse mêlée d'un sentiment de déception ou d'injustice du sort", "nom f"],
                    ["Affliction", "chagrin profond", "nom f"],
                    ["Allégresse", "joie très vive qu'on a envie d'exprimer", "nom f"],
                    ["Affectivité", "ensemble de sentiments (par opposition au raisonnement)", "nom f"],
                    ["Furibond(e)", "qui est tellement furieux qu'il en est un peu comique", "adjectif"],
                    ["Dubitatif(ve)", "qui exprime le doute, l'incertitude", "adjectif"],
                    ["Burlesque", "qualifie une situation ou une oeuvre qui fait rire par son extravagance", "adjectif"],
                    ["Pathétique", "qui émeut profondément, qui bouleverse, suscite la pitié", "adjectif"],
                    ["Prosaïque", "qui manque de poésie, bien plat, bien commun", "adjectif"],
                    ["Scabreux(se)", "qui présente des risques; qui choque la décence", "adjectif"],
                    ["Trivial", "vulgaire, grossier", "adjectif"],
                    ["Xénophobie", "sentiment d'hostilité à l'égard des étrangers", "nom f"],
                    ["Sollicitude", "attitude affectueuse et attentive envers une personne", "nom f"],
                    ["Tolérance", "comportement qui consiste à accepter des opinions ou des pratiques que l'on ne partage pas", "nom f"],
                    ["Élection", "synonyme de choix (vieilli)", "nom f"],
                    ["Enclin(e)", "qui est porté à un comportement, comme un penchant naturel", "adjectif"],
                    ["Appréhender", "envisager un évènement avec anxiété, redouter, craindre", "verbe"],
                    ["Sidérer", "frapper de stupeur", "verbe"],
                    ["Méduser", "synonyme de pétrifier, stupéfier", "verbe"],
                    ["Jubiler", "ressentir une joie très vive", "verbe"],
                    ["Déplorer", "regretter vivement", "verbe"],
                    ["Offusquer", "froisser, choquer ou causer des blessures d'amour-propre", "verbe"],
                    ["Affecter", "toucher, attrister", "verbe"],
                    ["Abhorrer", "avoir horreur, exécrer, haïr", "verbe"],
                    ["S'emporter", "se mettre en colère", "verbe"],
                    ["Pâtir", "éprouver une souffrance morale, subir les conséquences fâcheuses d'une action", "verbe"],
                    ["Révérer", "ressentir un respect et une admiration presque religieuse", "verbe"],
                    ["Exécrer", "ressentir la haine la plus vive (littéraire)", "verbe"],
                    ["Désintéressement", "qualité d'un acte ou d'une personne qui ne cherche pas son intérêt personnel, son profit", "nom m"],
                    ["Désintérêt", "indifférence, détachement, le fait de ne pas s'intéresser à qqch", "nom m"],
                    ["Inclination", "penchant concernant la vie morale ou les sentiments", "nom f"],
                    ["Inclinaison", "état de ce qui est incliné, penché", "nom f"],
                    ["Ressentiment", "rancune, souvenir très vif des torts ou des injures", "nom m"],
                    ["Sensation", "impression produite principalement par l'un des cinq sens", "nom f"],
                    ["Sensibilité", "aptitude à ressentir des impressions physiques ou affectives", "nom f"],
                    ["Sensualité", "tendance du tempérament à apprécier les plaisirs donnés par les sens", "nom f"],
                    ["Sentiment", "état de la vie affective (plus durable et plus complexe qu'une sensation)", "nom m"],
                    ["Compassion", "aptitude à percevoir ce que ressent une autre personne, notamment si elle souffre", "nom f"],
                    ["Convoitise", "envie très violente de posséder ce qui est hors de portée", "nom f"],
                    ["Dérision", "attitude de mépris ironique qui cherche à provoquer la moquerie", "nom f"],
                    ["Frustration", "sentiment pénible résultant de la privation d'une satisfaction", "nom f"],
                    ["Racisme", "théorie selon laquelle il existe des races supérieures à d'autres", "nom m"],
                    ["Sérénité", "calme total de l'esprit exempt de tout souci et de toute préoccupation", "nom f"],
                    ["Spleen", "mélancolie sans cause, accompagnée du dégoût de la réalité", "nom m"],
                    ["Volupté", "plaisir de sens ou de l'esprit", "nom f"]
                ]
            }
        }
    },
    'chap19': {
        title: 'Chapitre 19',
        selectorId: 'chap19SelectBtn',
        subcategories: {
            'noms': {
                name: 'Noms',
                color: '#FF8C00',
                alert: {
                    message: "l'évaluation est déjà passée. Le site supporte toujours la liste de voc mais cette liste est obsolète pour la prochaine évaluation",
                    color: '#FF8C00'
                },
                data: [
                    ["Damnation", "la condamnation à l'enfer", "nom"],
                    ["Dogmes", "les vérités fondamentales, les croyances obligatoires", "nom"],
                    ["Ferveur", "l'ardeur, l'enthousiasme religieux", "nom"],
                    ["Genèse", "élaboration de quelque chose", "nom"],
                    ["Sacerdoce", "une fonction presque religieuse", "nom"],
                    ["Tabou", "quelque chose d'interdit", "nom"],
                    ["Éden", "sens propre : nom propre du paradis terrestre ; sens figuré : lieu qui apparaît comme un paradis", "nom"],
                    ["Apôtre", "sens propre : disciple du Christ envoyé par lui pour prêcher (enseigner) l'Évangile ; sens figuré: personne qui propage ou défend une doctrine", "nom"],
                    ["Foi", "sens général : confiance. Sens spécialisé en religion : croyance résultant d'une adhésion profonde du coeur et de l'esprit, certitude intérieure.", "nom"],
                    ["Rite", "règle(s) d'une cérémonie ou manière de faire invariable.", "nom"],
                    ["Fortune", "le sort, le hasard, personnifiés sous l'Antiquité par une déesse représentée les yeux bandés.", "nom"],
                    ["Bible", "Sens propre : ensemble des textes sacrés des religions juives et chrétiennes (étymologiquement : 'les livres') ; sens figuré : ouvrage faisant autorité, auquel on se réfère.", "nom"],
                    ["Idée", "synonyme de concept, ce qui est élaboré par la pensée.", "nom"],
                    ["Méditation", "réflexion solitaire et recueillie.", "nom"],
                    ["Sagesse", "disposition consistant à se connaître et à savoir bien mourir et bien vivre, selon Montaigne.", "nom"],
                    ["Salut", "ce qui permet d'être sauvé, d'échapper à un danger et de trouver un état heureux. Dans le christianisme : fait d'échapper à la damnation éternelle.", "nom"],
                    ["Relique", "sens propre : reste d'un saint, d'un héros qui est l'objet d'un culte ; sens figuré : objet auquel on attache un grand prix comme témoin du passé.", "nom"],
                    ["Intégrisme", "position de croyants qui, au nom d'un respect intransigeant de la tradition, se refusent à toute évolution dans l'interprétation des textes.", "nom"],
                    ["Hérésie", "Sens propre : doctrine ou interprétation contraire aux dogmes d'une religion et condamnée comme telle ; sens figuré : opinion, théorie qui heurte la raison.", "nom"],
                    ["Doctrine", "Ensemble des croyances ou des opinions qu'on affirme comme vraies et sur lesquelles on s'appuie pour interpréter des faits ou pour agir.", "nom"],
                    ["Métaphysique", "Recherche rationnelle sur des sujets qui se situent au-delà de la réalité concrète donc sur des abstractions telles que les principes de la connaissance, l'existence de Dieu.", "nom"],
                    ["Déterminisme", "doctrine ou opinion selon laquelle les phénomènes ou les actions humaines sont conditionnés par des éléments antérieurs ou par d'autres phénomènes ; désigne aussi, au pluriel, l'ensemble des causes concrètes préalable à un phénomène.", "nom"],
                    ["Fétichisme", "Sens propre : culte d'objets auxquels on attribue un pouvoir surnaturel ; sens figuré : attachement exagéré pour une entité, une personne ou un objet.", "nom"],
                    ["Holocauste", "Sens propre : dans la religion juive ancienne, sacrifice où la victime (animal) était entièrement brûlée ; sens figuré : sacrifice total. Désigne par analogie l'extermination des Juifs sous le régime nazi, la Shoah.", "nom"],
                    ["Iconoclaste", "Sens propre : qui interdit le culte des images saintes, notamment les statues ; par extension : qui détruit les oeuvres d'art ; sens figuré : qui se refuse à toute tradition.", "nom"],
                    ["Parabole", "Récit allégorique destiné à donner un enseignement sous une forme imagée.", "nom"],
                    ["Prosélytisme", "Sens propre : zèle déployé par une personne récemment convertie à une religion pour faire de nouveaux adeptes ; sens figuré : s'emploie aussi dans le domaine de la politique ou des opinions en général.", "nom"],
                    ["Âme", "dans le christianisme, principe spirituel immortel qui se sépare du corps à la mort et qui est jugé par Dieu. Plus largement : principe de vie qui anime l'être vivant, part de la pensée, de la sensibilité et de la conscience morale.", "nom"],
                    ["Ascète", "Personne qui s'impose, par piété et pour faire pénitence, des privations, des sacrifices (sens propre) ; personne qui mène une vie austère en se privant de tous les plaisirs terrestres (sens figuré).", "nom"],
                    ["Culte", "Ensemble de pratiques religieuses destinées à rendre hommage à une divinité (sens propre) ; vénération pour une personne ou une entité que l'on aime et que l'on respecte (sens figuré).", "nom"],
                    ["Entité", "Concept que l'on considère dans sa totalité et dont on parle comme d'un être réel.", "nom"],
                    ["Fanatisme", "Passion excessive inspirée notamment par une religion ou une doctrine et qui conduit à la violence.", "nom"],
                    ["Idéologie", "Système d'idées sur lequel se fonde un groupe social pour juger et agir (sens moderne).", "nom"],
                    ["Initiation", "Processus d'introduction à la connaissance de mystères, de savoirs réservés à un petit cercle.", "nom"],
                    ["Liturgie", "Cérémonial des offices religieux (sens propre). Peut se dire aussi de cérémonials de fêtes ayant une certaine solennité (sens figuré).", "nom"],
                    ["Magie", "Art ou pouvoir inexpliqué, merveilleux, occulte, par opposition à un processus logique et rationnel.", "nom"],
                    ["Oracle", "Dans l'Antiquité, réponse d'une divinité interrogée dans un sanctuaire ; opinion considérée avec beaucoup de respect, en laquelle on a confiance (parfois ironique).", "nom"],
                    ["Pardon", "Décision qui consiste à renoncer à éprouver de la rancune ou de l'hostilité à l'égard d'une personne qui vous à fait du mal. Sens religieux : absolution des pêchés.", "nom"],
                    ["Philosophie", "Réflexion abstraite sur les fondements du monde et les valeurs humaines, qui a pour but d'élaborer une 'sagesse', c'est-à-dire un système de valeurs personnel, un art de vivre.", "nom"]
                ]
            },
            'adj_verbes': {
                name: 'Adjectifs et Verbes',
                color: '#FF8C00',
                alert: {
                    message: "l'évaluation est déjà passée. Le site supporte toujours la liste de voc mais cette liste est obsolète pour la prochaine évaluation",
                    color: '#FF8C00'
                },
                data: [
                    ["absurde", "insensée, déraisonnable, contraire à la logique", "adjectif"],
                    ["athée", "qui ne croit en aucun dieu", "adjectif"],
                    ["augurer", "prévoir", "verbe"],
                    ["dominicale", "ce que l'on fait le dimanche", "adjectif"],
                    ["immanente", "qui est contenu dans toute chose", "adjectif"],
                    ["manichéen", "qui oppose systématiquement et sans nuances deux points de vue opposés", "adjectif"],
                    ["néophyte", "un nouveau converti à une religion ou une doctrine", "adjectif"],
                    ["pieuse", "pleine de dévotion, de ferveur religieuse", "adjectif"],
                    ["profane", "ne pas s'y connaître, ne pas avoir été initié à un art", "adjectif"],
                    ["vénielle", "peu grave", "adjectif"],
                    ["gratuit", "qui ne se paie pas, qui ne demande pas d'effort pour être obtenu ; par extension : acte accompli sans raison, sans mobile.", "adjectif"],
                    ["mystique", "personne qui atteint un état de communication intuitive et immédiate avec la divinité par la force de sa croyance.", "adjectif"],
                    ["spirituelle", "se dit de la vie de l'âme ou de la vie morale", "adjectif"],
                    ["puritain(ne)", "qualifie un respect rigoureux des principes moraux par allusion à une secte pratiquant un christianisme très 'pur'", "adjectif"],
                    ["païenne", "qui ne fait pas partie des trois religions révélées. Par extension : qui n'a pas de religion", "adjectif"],
                    ["prophétique", "qui prédit l'avenir", "adjectif"],
                    ["se repentir", "regretter profondément d'avoir accompli une action (connotation religieuse)", "verbe"],
                    ["profaner", "porter atteinte à un lieu ou un objet sacré", "verbe"],
                    ["vénérer", "aimer avec un grand respect une personne ou une chose (connotation religieuse)", "verbe"],
                    ["blasphémer", "dans la langue religieuse : prononcer des paroles sacrilèges qui outragent ce qui est sacré", "verbe"],
                    ["édifier", "donner un bon exemple moral", "verbe"],
                    ["absoudre", "donner le sacrement de pénitence, c'est-à-dire pardonner les péchés ou les fautes (langue religieuse)", "verbe"],
                    ["expier", "payer un crime ou une faute par un châtiment, une peine ou une réparation.", "verbe"],
                    ["immoler", "langue littéraire et religieuse : faire périr une victime en sacrifice à un dieu ; sens figuré : faire périr une personne pour une cause", "verbe"],
                    ["abjurer", "abandonner solennellement une opinion, une religion", "verbe"],
                    ["idolâtrer", "adorer quelqu'un, en faire son dieu", "verbe"],
                    ["impie", "qui n'est pas croyant ou qui offense la religion (vieilli ou religieux)", "adjectif"]
                ]
            }
        }
    },
    'chap20': {
        title: 'Chapitre 20',
        selectorId: 'chap20SelectBtn',
        subcategories: {
            'general': {
                name: 'Vocabulaire Général',
                color: '#BB86FC',
                alert: {
                    message: "l'évaluation est déjà passée. Le site supporte toujours la liste de voc mais cette liste est obsolète pour la prochaine évaluation",
                    color: '#FF8C00'
                },
                data: [
                    ["Acception", "la signification d'un mot, d'un concept", "nom"],
                    ["Bibliographie", "une liste des ouvrages écrits sur ce sujet", "nom"],
                    ["Critique", "l'avis qu'une œuvre a reçu, pouvant être négatif ou positif", "nom"],
                    ["Leitmotiv", "une formule revenant plusieurs fois dans un texte pour créer un effet comique ou dramatique", "nom"],
                    ["Mécène", "une personne ou une institution qui aide financièrement et protège un ou plusieurs artistes", "nom"],
                    ["Média", "un support de communication", "nom"],
                    ["Mythe", "un récit qui idéalise les actions du personnage", "nom"],
                    ["Plagiat", "la copie et l'accaparation de l'œuvre d'autrui", "nom"],
                    ["Psychanalyse", "l'interprétation de la vie psychique", "nom"],
                    ["Suspense", "un moment d'attente qui suspend le déroulement d'une action ou précède son dénouement et tient le spectateur en haleine", "nom"],
                    ["Humour", "disposition d'esprit qui consiste à faire apparaître les aspects drôles ou insolites de la réalité, par exemple en prenant au sérieux ce qui ne l'est pas et vice versa", "nom"],
                    ["Ironie", "manière de critiquer une chose ou de s'en moquer en disant le contraire de ce que l'on pense, en faisant comme si l'on était d'accord avec le point de vue opposé", "nom"],
                    ["Parodie", "sens propre: imitation burlesque d'une œuvre sérieuse; sens figuré: imitation regrettable d'une action respectable", "nom"],
                    ["Réalisme", "volonté de donner dans une œuvre une vision exacte de la réalité telle qu'elle est, d'où parfois une certaine tendance à insister sur les aspects grossiers, répugnants de la réalité", "nom"],
                    ["Utopie", "gouvernement imaginaire et idéal / conception ou projet qui paraît irréalisable, mais qui peut pourtant être fructueux; parfois employé avec une nuance péjorative", "nom"],
                    ["Satire", "type d'écrit ou de discours qui critique une personne, une œuvre ou une institutions, en s'en moquant avec verve et virulence", "nom"],
                    ["Culture", "aventure personnelle qui tend à développer les qualités naturelles de l'individu, à le mettre en état de croissance intellectuels (selon Madeleine Hours)", "nom"],
                    ["Civilisation", "ensemble des aspects religieux et moraux, intellectuels, scientifiques et techniques ainsi que des pratiques sociales commune à un peuple ou à un groupe de peuples (peut sous entendre le progrès par rapport à un état primitif)", "nom"],
                    ["Connotation", "ensemble des valeurs affectives attachées à un mot en plus de son sens propre", "nom"],
                    ["Ellipse", "omission d'un mot qui se trouve ainsi sous-entendu; raccourci ou sous-entendu dans un récit ou un film", "nom"],
                    ["Litote", "expression modéré d'une situation extrême", "nom"],
                    ["Métaphore", "comparaison condensée, figure de style fréquente en poésie", "nom"],
                    ["Néologisme", "mot nouveau ou sens nouveau d'un mot déjà existant", "nom"],
                    ["Symbole", "signe concret évoquant par un rapport qui paraît naturel quelque chose d'invisible; objet ou image de la réalité ayant des correspondance avec la vie intérieure", "nom"],
                    ["Érudit", "qui a des connaissances approfondies dans une matière", "adjectif"],
                    ["Péjoratif", "dévalorisant", "adjectif"],
                    ["Référer", "consulter pour y trouver des indications sur lesquelles vous appuyer", "verbe"],
                    ["Lyrique", "sens propre : œuvre destinée à être chantée; sens figuré: œuvre exprimant des sentiments intimes de manière à communiquer une émotion", "adjectif"],
                    ["Didactique", "qualifie un discours ou un texte dont la principale visée est d'instruire", "adjectif"],
                    ["Dramatique", "sens propre; qui a un rapport avec le théâtre; sens figuré: qualifie une action dont l'issue est incertaine, une lutte contre la mort qui émeut ceux qui en sont témoins", "adjectif"],
                    ["Épique", "qualifie une œuvre qui met en scène des événements historiques ou légendaires en mettant en valeur leur caractère grandiose ou héroïque; s'applique aussi à d'autres formes d'art (ex: cinéma).", "adjectif"],
                    ["Fantastique", "créé par l'imagination, qui n'existe pas dans la réalité, souvent avec connotation de bizarre, d'inquiétant.", "adjectif"],
                    ["Merveilleux", "qui étonne ou enchante par son caractère magique ou miraculeux, avec la connotation d'heureux ou d'admirable", "adjectif"],
                    ["Romanesque", "sens propre: qui se trouve dans les romans; sens figuré (avec nuances parfois péjorative): qualifie un esprit qui a tendance à s'évader de ka réalité, à se complaire dans un monde plus agréable que la réalité, comme on en trouve dans les romans", "adjectif"],
                    ["Tragique", "qualifie la situation d'un être qui paraît victime de la fatalité, qui s'efforce en vain d'échapper à son destin", "adjectif"],
                    ["Épistolaire", "qui concerne la correspondance", "adjectif"],
                    ["Euphémique", "expression atténuée pour parler d'une réalité déplaisante", "adjectif"]
                ]
            }
        }
    }
};
